name: gem_tools
owner: AlmaasLab
homepage_url: https://github.com/AlmaasLab/elixir-galaxy-tools-systemsbiology
remote_repository_url: https://github.com/AlmaasLab/elixir-galaxy-tools-systemsbiology
type: unrestricted
description: Tools for analyzing genome-scale metabolic models (GEMs) using COBRApy and related libraries.
long_description: |
  This repository contains a collection of Galaxy tools for performing various analyses on genome-scale metabolic models (GEMs). The tools leverage COBRApy and other Python libraries to provide functionalities such as phenotype phase plane analysis, gene knockout analysis, flux variability analysis, and more.
categories:
  - Metabolomics
  - Systems Biology
  - Flux Balance Analysis
license: GNU GENERAL PUBLIC LICENSE